# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L93ZS2jlC3tlVw7DT2iQSuDXXTF10bpE
"""

#1 area of rectangle
length = float(input("Enter length: "))
breadth = float(input("Enter breadth: "))

area = length * breadth

print("Area of Rectangle =", area)

#2 simple intrest
principal = float(input("Enter Principal Amount: "))
rate = float(input("Enter Rate of Interest: "))
time = float(input("Enter Time (in years): "))

si = (principal * rate * time) / 100

print("Simple Interest =", si)

#3 Convert Celsius to Fahrenheit
celsius = float(input("Enter temperature in Celsius: "))

fahrenheit = (9/5) * celsius + 32

print("Temperature in Fahrenheit =", fahrenheit)

#4 Calculate Average of 3 Numbers
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))

average = (num1 + num2 + num3) / 3

print("Average =", average)

#5 Find Square and Cube of a Number
num = int(input("Enter a number: "))

square = num ** 2
cube = num ** 3

print("Square =", square)
print("Cube =", cube)

#6 Swap Two Numbers Without Using Third Variable
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

a = a + b
b = a - b
a = a - b

print("After Swapping:")
print("a =", a)
print("b =", b)

#7 Student Report Program

name = input("Enter Student Name: ")
roll_no = input("Enter Roll Number: ")

# Marks of 5 subjects
m1 = float(input("Enter marks of Subject 1: "))
m2 = float(input("Enter marks of Subject 2: "))
m3 = float(input("Enter marks of Subject 3: "))
m4 = float(input("Enter marks of Subject 4: "))
m5 = float(input("Enter marks of Subject 5: "))

# Calculate total marks
total = m1 + m2 + m3 + m4 + m5

# Calculate percentage
percentage = (total / 500) * 100

# Display Report
print("\n------ STUDENT REPORT ------")
print("Name:", name)
print("Roll No:", roll_no)
print("Total Marks:", total)
print("Percentage:", percentage, "%")